/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainTicketBookingSystem;

import DB_Connection.ConnectionProvider;
import java.sql.*;
import java.text.DateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import java.util.Date;
import java.util.*;

import java.io.*;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

/**
 *
 * @author welcom
 */
public class User_BookTrain extends javax.swing.JFrame {

    public int flag = 0;

    /**
     * Creates new form AddDiagonisis
     */
    public User_BookTrain() {
        initComponents();
        redlabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        redlabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        wardlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainTicketBookingSystem/x_close.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search by Train Name : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        redlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        redlabel.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(redlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 210, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 100, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainTicketBookingSystem/x_searchicon.png"))); // NOI18N
        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 120, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 720, 50));

        wardlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wardlabel.setForeground(new java.awt.Color(255, 255, 255));
        wardlabel.setText("Coach");
        getContentPane().add(wardlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-Mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 70, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 210, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 210, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 210, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC First Class", "AC 2 Tier", "First Class", "Sleeper" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 50, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainTicketBookingSystem/x_tick_icon.jpg"))); // NOI18N
        jButton3.setText("Book Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 150, 30));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No.of.Tickets");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Today's Fare");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 90, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 70, 20));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 120, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainTicketBookingSystem/x_modules_bg.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void sendPlainTextEmail(String host, String port,
            final String userName, final String password, String toAddress,
            String subject, String message) throws AddressException,
            MessagingException {

        // sets SMTP server properties
        Properties properties = new Properties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", port);
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");

        properties.put("mail.smtp.user", userName);

        // creates a new session, no Authenticator (will connect() later)
        Session session = Session.getDefaultInstance(properties);

        // creates a new e-mail message
        Message msg = new MimeMessage(session);

        msg.setFrom(new InternetAddress(userName));
        InternetAddress[] toAddresses = {new InternetAddress(toAddress)};
        msg.setRecipients(Message.RecipientType.TO, toAddresses);
        msg.setSubject(subject);
        msg.setSentDate(new Date());
        // set plain text message
        msg.setText(message);

        // sends the e-mail
        Transport t = session.getTransport("smtp");
        t.connect(userName, password);
        t.sendMessage(msg, msg.getAllRecipients());
        t.close();

    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String trainName = jTextField1.getText();
        int count = 0;
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from priya.traindetails where priya.traindetails.trainname='" + trainName + "' ");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            String fare = jTable1.getValueAt(0, 3).toString();

            flag = 1;
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Train doesn't exist!");
                redlabel.setVisible(true);
            } else {
                redlabel.setVisible(false);
                jTextField1.setEditable(false);
                //System.out.println("fare"+fare);
                int todaysfare = Integer.parseInt(fare);
                int currdate = Integer.parseInt(java.time.LocalDate.now().toString().substring(8, 10));

                double temp = (double) 20 / 100;

                double percentageinc = todaysfare * temp;
                if (currdate < 8 || currdate > 25) {
                    todaysfare += percentageinc;
                }

                //System.out.println(todaysfare);
                jTextField5.setText(Integer.toString(todaysfare));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //String name=
        if (flag == 1) {
            String trainName = jTable1.getValueAt(0, 0).toString();;
            String source = jTable1.getValueAt(0, 1).toString();;
            String destination = jTable1.getValueAt(0, 2).toString();;

            String amount = jTextField5.getText();
            String name = jTextField2.getText();
            String mailid = jTextField3.getText();
            String phone = jTextField4.getText();
            String date = DateFormat.getDateInstance().format(jDateChooser1.getDate());
            String coach = jComboBox1.getSelectedItem().toString();
            String numberoftickets = jSpinner1.getValue().toString();
            System.out.println(" " + name + " " + mailid + " " + trainName + " " + source + " " + destination + " " + amount + " " + phone + " " + date + " " + coach + " " + numberoftickets);
            java.util.Date datee = new java.util.Date();
            String temp = datee.toString();
            String curdate = temp.substring(8, 10) + " " + temp.substring(4, 7) + ", " + temp.substring(24);
            String strPattern = "^0+(?!$)";
            curdate = curdate.replaceAll(strPattern, "");
            //chechk for ticket availability
            try {
                Connection con2 = ConnectionProvider.getCon();
                Statement st2 = con2.createStatement();
                ResultSet rs = st2.executeQuery("select remainingtickets from ticketmanager where trainname='" + trainName + "' and date='" + date + "'");
                //if no record
                if (!rs.next()) {
                    try {
                        Connection con = ConnectionProvider.getCon();
                        Statement st = con.createStatement();
                        st.executeUpdate("insert into ticketmanager values('" + trainName + "','" + date + "','" + (10-Integer.parseInt(numberoftickets)) + "')");
                        //JOptionPane.showMessageDialog(null, "Succesfully Added");
                        setVisible(false);
                        new Admin_AddTrain().setVisible(true);

                    } catch (Exception e) {
                        System.out.println(e);

                        JOptionPane.showMessageDialog(null, "Enter correct data");
                    }
                }
                //if record exists
                else {
                    int remticket=0;
                    while (rs.next()) {
                         remticket = Integer.parseInt(rs.getString(1));
                    }
                    //no tickets
                    if (Integer.parseInt(numberoftickets) > remticket) {
                        JOptionPane.showMessageDialog(null, "Ticket out of stock");
                        return;
                        ////////////////
                    }
                    //have tickets
                    else {
                        try {
                            remticket-=Integer.parseInt(numberoftickets);
                            Connection con = ConnectionProvider.getCon();
                            Statement st = con.createStatement();
                            st.executeUpdate("update ticketmanager set remainingtickets='" + remticket + "' where trainname='" + trainName + "' and date='"+date+"'");
                            JOptionPane.showMessageDialog(null, "Successfully Updated");
                            setVisible(false);
                            new Admin_EditTrain().setVisible(true);

                        } catch (Exception e) {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog(null, "Enter data in correct format");
                        }
                        
                        //one ticket one day
                    }
                }
                //one ticket one day
                try {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                ResultSet rss = st.executeQuery("select mailid,bookeddate from bookingdetails where mailid='" + mailid + "' and bookeddate='" + curdate + "'");
                System.out.println("getrow : " + rss.getRow());
                if (!rss.next()) {
                    //System.out.println("entererd re.next()");
                    try {
                        Connection con1 = ConnectionProvider.getCon();
                        Statement st1 = con1.createStatement();
                        st1.executeUpdate("insert into bookingdetails values('" + name + "','" + mailid + "','" + trainName + "','" + source + "','" + destination + "','" + amount + "','" + date + "','" + coach + "','" + numberoftickets + "','" + phone + "','" + curdate + "')");
                        JOptionPane.showMessageDialog(null, "Succesfully Added");
                        setVisible(false);
                        new Admin_AddTrain().setVisible(true);

                    } catch (Exception e) {
                        System.out.println(e);

                        JOptionPane.showMessageDialog(null, "Enter correct data");
                    }
            //send booking details
            String host = "smtp.gmail.com";
            String port = "587";
            String mailFrom = "priyashan0312@gmail.com";
            String password = "Niwhsarajayirp800@gmail.com";

            // outgoing message information
            String mailTo = mailid;
            String subject = "Ticket Booking Confirmation";
            String message = "Passenger Name : " + name + "\nMailid : " + mailid + "\nPhone Number : "
                    + phone + "\nTrain Name : " + trainName + "\nSource Location : "
                    + source + "\nDestination location : " + destination + "\nDate : " + date + "\nAmount : "
                    + amount + "\nCoach : " + coach + "\nNo.Of.Tickets : "
                    + numberoftickets + "\n\n\n\n ---- HAPPY JOURNEY ----:)";

            User_BookTrain mailer = new User_BookTrain();

            try {
                mailer.sendPlainTextEmail(host, port, mailFrom, password, mailTo,
                        subject, message);
                System.out.println("Email sent.");
            } catch (Exception ex) {
                System.out.println("Failed to sent email.");
                ex.printStackTrace();
            }
                } else {
                    JOptionPane.showMessageDialog(null, "Users can book only one ticket for a particular date.. You have booked already for today ! Please try again next day !");
                    try{
          Connection con3=ConnectionProvider.getCon();
          Statement st3=con3.createStatement();
          st3.executeUpdate("delete from ticketmanager where trainname='"+trainName+"' and date='"+date+"'");
          //JOptionPane.showMessageDialog(null,"Succesfully deleted");
          setVisible(false);
          new Admin_AddTrain().setVisible(true);
          
        }
        catch(Exception e){
            System.out.println(e);
                    
        JOptionPane.showMessageDialog(null,"Enter correct data");
        }        
                }

            } catch (Exception e) {

            }
            } catch (Exception e) {
                System.out.println(e);
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_BookTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_BookTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_BookTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_BookTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_BookTrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel redlabel;
    private javax.swing.JLabel wardlabel;
    // End of variables declaration//GEN-END:variables
}
